/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug  8 2014, 14:49:54                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "function.h"
#include "ui.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0            (GUI_ID_USER + 0x00)
#define ID_TEXT_0            (GUI_ID_USER + 0x01)
#define ID_TEXT_1		 (GUI_ID_USER + 0x05)
#define ID_BUTTON_0            (GUI_ID_USER + 0x02)
#define ID_BUTTON_1			   (GUI_ID_USER + 0x03)
#define ID_BUTTON_2			   (GUI_ID_USER + 0x04)
#define ID_BUTTON_3			   (GUI_ID_USER + 0x06)		
#define ID_PROGBAR_0		   (GUI_ID_USER + 0x07)

#define BUTTON_PRESSED	1
#define BUTTON_UNPRESSED 0


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 320, 240, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 57, 16, 160, 33, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 150, 60, 100, 33, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 60, 60, 75, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 60, 100, 75, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_2, 60, 140, 75, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_3, 150, 140, 75, 25, 0, 0x0, 0 },
  { PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 84, 180, 134, 20, 0, 0x0, 0 },
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem,hItemText,hItemButton;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
	  case WM_INIT_DIALOG:
		//
		// Initialization of 'Framewin'
		//
		hItem = pMsg->hWin;
		FRAMEWIN_SetTitleHeight(hItem, 20);
		FRAMEWIN_SetText(hItem, "Whiteleg Tech");
		FRAMEWIN_SetFont(hItem, GUI_FONT_20_ASCII);
		FRAMEWIN_SetTextColor(hItem, 0x000000FF);
		FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetText(hItem, "Status: Idling");
		TEXT_SetFont(hItem, GUI_FONT_20_ASCII);
		TEXT_SetTextColor(hItem, 0x00FF0000);
		//
		// Initialization of 'Text1'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetText(hItem, GetSDSectorCount());
		TEXT_SetFont(hItem, GUI_FONT_20_ASCII);
		TEXT_SetTextColor(hItem, 0x00FF0000);
		//
		// Initialization of 'Button0'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		BUTTON_SetFont(hItem, GUI_FONT_20_ASCII);
		BUTTON_SetText(hItem, "Record");
		//
		// Initialization of 'Button1'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		BUTTON_SetFont(hItem, GUI_FONT_20_ASCII);
		BUTTON_SetText(hItem, "Play");
		//
		// Initialization of 'Button2'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
		BUTTON_SetFont(hItem, GUI_FONT_20_ASCII);
		BUTTON_SetText(hItem, "Stop");
		//BUTTON_SetPressed(hItem, BUTTON_PRESSED);
		//
		// Initialization of 'Button3'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
		BUTTON_SetFont(hItem, GUI_FONT_20_ASCII);
		BUTTON_SetText(hItem, "Clear");
		//BUTTON_SetPressed(hItem, BUTTON_PRESSED);
		// USER START (Optionally insert additional code for further widget initialization)
		// USER END
		break;
	  // USER START (Optionally insert additional message handling)
	  case WM_NOTIFY_PARENT:
		  Id = WM_GetId(pMsg->hWinSrc);
		  NCode = pMsg->Data.v;
		  switch(Id){
			  case ID_BUTTON_0:
				  switch(NCode){
					  case WM_NOTIFICATION_CLICKED:
						  break;
					  case WM_NOTIFICATION_RELEASED:
						  hItemText = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
						  TEXT_SetText(hItemText, "Status: Recording");
						  hItemButton = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
					      BUTTON_SetPressed(hItemButton, BUTTON_PRESSED);
						  hItemButton = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
						  BUTTON_SetPressed(hItemButton, BUTTON_UNPRESSED);
					      //hItemButton = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
						  //BUTTON_SetPressed(hItemButton, BUTTON_UNPRESSED);
						  hItemText = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
					      TEXT_SetText(hItemText, GetSec());
					      status_toAdc();
						  break;
					  default:
						  break;
				  }
				  break;
			  case ID_BUTTON_1:
				  switch(NCode){
					  case WM_NOTIFICATION_CLICKED:
						  break;
					  case WM_NOTIFICATION_RELEASED:
						  hItemText = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
						  TEXT_SetText(hItemText, "Status: Playing");
					      hItemButton = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
					      BUTTON_SetPressed(hItemButton, BUTTON_PRESSED);
						  hItemButton = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
						  BUTTON_SetPressed(hItemButton, BUTTON_UNPRESSED);
					      //hItemButton = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
						  //BUTTON_SetPressed(hItemButton, BUTTON_UNPRESSED);
						  hItemText = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
					      TEXT_SetText(hItemText, GetSec());
					      status_toDac();
						  break;
					  default:
						  break;
				  }
				  break;
			  case ID_BUTTON_2:
				  switch(NCode){
					  case WM_NOTIFICATION_CLICKED:
						  break;
					  case WM_NOTIFICATION_RELEASED:
						  hItemText = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
						  TEXT_SetText(hItemText, "Status: Idling");
						  hItemButton = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
					      BUTTON_SetPressed(hItemButton, BUTTON_UNPRESSED);
						  hItemButton = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
						  BUTTON_SetPressed(hItemButton, BUTTON_UNPRESSED);
						  //hItemButton = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
						  //BUTTON_SetPressed(hItemButton, BUTTON_PRESSED);
						  hItemText = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
					      TEXT_SetText(hItemText, GetSec());
					      touch_stop();
						  break;
					  default:
						  break;
				  }
				  break;
			  case ID_BUTTON_3:
				  switch(NCode){
					  case WM_NOTIFICATION_CLICKED:
						  break;
					  case WM_NOTIFICATION_RELEASED:
						  Clear_SD();
						  hItemButton = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
					      BUTTON_SetPressed(hItemButton, BUTTON_UNPRESSED);
						  hItemButton = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
						  BUTTON_SetPressed(hItemButton, BUTTON_UNPRESSED);
						  hItemText = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
					      TEXT_SetText(hItemText, "Cleared!");
						  break;
					  default:
						  break;
				  }
				  break;
			  default:
				  break;
		  }
		  break;
	  // USER END
	  default:
		WM_DefaultProc(pMsg);
		break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
WM_HWIN CreateFramewin(void);
WM_HWIN CreateFramewin(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
